Repository cert-manager/webhook-cert-lib, pull requests merged in 2025-07, with the labels that each got.

#2 Bump all dependencies to latest versions
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: dco-signoff: yes, size/L

#4 Add makefile modules
  .github/dependabot.yaml
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  .golangci.yaml
  Makefile
  OWNERS
  OWNERS_ALIASES
  klone.yaml
  make/00_mod.mk
  make/02_mod.mk
  make/_shared/boilerplate/00_mod.mk
  make/_shared/boilerplate/01_mod.mk
  make/_shared/boilerplate/template/boilerplate.go.txt
  make/_shared/generate-verify/00_mod.mk
  make/_shared/generate-verify/02_mod.mk
  make/_shared/generate-verify/util/verify.sh
  make/_shared/go/.golangci.override.yaml
  make/_shared/go/01_mod.mk
  make/_shared/go/README.md
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/help/01_mod.mk
  make/_shared/help/help.sh
  make/_shared/klone/01_mod.mk
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base-dependabot/.github/dependabot.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/LICENSE
  make/_shared/repository-base/base/Makefile
  make/_shared/repository-base/base/OWNERS_ALIASES
  make/_shared/tools/00_mod.mk
  make/_shared/tools/util/checkhash.sh
  make/_shared/tools/util/hash.sh
  make/_shared/tools/util/lock.sh
  make/test-unit.mk
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#5 Fix CI issues
  internal/errors/errors.go
  internal/pki/cert_pool.go
  internal/pki/csr.go
  internal/pki/generate.go
  internal/pki/parse.go
  pkg/authority/api/api.go
  pkg/authority/authority.go
  pkg/authority/cert/tls.go
  pkg/authority/leader_controllers/ca_secret_controller.go
  pkg/authority/leader_controllers/injectable/injectable.go
  pkg/authority/leader_controllers/injectable/validating_webhook.go
  pkg/authority/leader_controllers/injectable_controller.go
  pkg/authority/leader_controllers/reconciler.go
  pkg/authority/leader_controllers/ssa_client.go
  pkg/authority/leaf_cert_controller.go
  test/ca_secret_controller_test.go
  test/injectable_controller_test.go
  test/leaf_cert_controller_test.go
  test/suite_test.go
  test/util_test.go
Labels: dco-signoff: yes, size/L, lgtm, approved

#9 Simplify certificate issuance
  pkg/authority/cert/tls.go
Labels: dco-signoff: yes, lgtm, approved, size/M
